### ISSUE TITLE
Stopped Updating

### ISSUE THREAD

**Issue by supersaiyandoyle** [daniellowtw/explosm-rss#6]
I know this is an old project, but the rss stopped updating about a month ago.

**Comment by Paynmayn** [comment]
The RSS feed, which this project is using as source, broke about a month ago.
https://www.reddit.com/r/CyanideandHappiness/comments/s6wz2o/whats_happening_with_joel/hu1k209/

**Comment by daniellowtw** [comment]
Indeed the underlying rss feed that this project is based on - http://feeds.feedburner.com/Explosm - has stopped updating since Dec 2021. I do not intend to fix this until there's more news from upstream about what the future of that feed is. Thank you @Paynmayn for that link that confirmed that they are looking into it.

While it is possible to generate a feed by polling the main site regularly during a day, it is a very flimsy solution that would break if the source updates the layout of the site.

Hence, let's wait a bit more to see what Kris and Dave plan to do. Let's hope they'll expose a feed that includes the image rather than a link.

**Comment by tsuliwaensis** [comment]
The RSS is back up at [https://explosm.net/rss.xml](https://explosm.net/rss.xml)

**Comment by daniellowtw** [comment]
@tsuliwaensis Thanks for the notification. I've updated the upstream feed and this feed should be working again.

**Comment by daniellowtw** [comment]
https://github.com/daniellowtw/explosm-rss/commit/92bb7e7d123f19fa2ab467c5782cd9c2f509fb17 fixes the issue.
